version: '3.8'
#Version indicates what features we can use
services:
  #Children here are the containers
  mysql:
    image: 'mysql:8.2.0'
    volumes:
      - /var/lib/mysql
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3200:3306'
    tty: true
